<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Longitudinal Tutorial - 3&nbsp; Marginal Model Interpretation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Longi_mixeffect.html" rel="next">
<link href="./Longi_GEE.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Longi_intro.html">Longitudinal Data Analysis</a></li><li class="breadcrumb-item"><a href="./Longi_GEEinterpretation.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Marginal Model Interpretation</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Longitudinal Tutorial</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./Longi_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Longitudinal Data Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_EDA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_GEE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Marginal Model (GEE)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_GEEinterpretation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Marginal Model Interpretation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_mixeffect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Mixed Effects Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparison Covariance and Marginal Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_covmodel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modeling the Covariance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_modelselection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Prediction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpretation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_noncontinuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Models for Non-Continuous Outcomes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Longi_missingdata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Missing Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#brief-review-of-what-we-learned" id="toc-brief-review-of-what-we-learned" class="nav-link active" data-scroll-target="#brief-review-of-what-we-learned"><span class="header-section-number">3.1</span> Brief Review of What We Learned</a></li>
  <li><a href="#interpreting-coefficients-of-marginal-models-systematic-component" id="toc-interpreting-coefficients-of-marginal-models-systematic-component" class="nav-link" data-scroll-target="#interpreting-coefficients-of-marginal-models-systematic-component"><span class="header-section-number">3.2</span> Interpreting Coefficients of Marginal Models (Systematic Component)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-longi-GEE-interpretation" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Marginal Model Interpretation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="brief-review-of-what-we-learned" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="brief-review-of-what-we-learned"><span class="header-section-number">3.1</span> Brief Review of What We Learned</h2>
<p></p>
<ul>
<li>Marginal Models
<ul>
<li>GLS
<ul>
<li>Define covariance model</li>
<li>Compare models using AIC, BIC, likelihood ratio test</li>
</ul></li>
<li>GEE
<ul>
<li>Compare models using QIC</li>
<li>Define covariance model and link function</li>
</ul></li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)  <span class="co">#used for the gls() function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpreting-coefficients-of-marginal-models-systematic-component" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="interpreting-coefficients-of-marginal-models-systematic-component"><span class="header-section-number">3.2</span> Interpreting Coefficients of Marginal Models (Systematic Component)</h2>
<p>First, lets consider a few simple cases in understanding the Marginal Model:</p>
<p><span class="math display">\[\mu_{ij} = E(\textcolor{red}{y}_{ij} \mid {X_{ij},t_{ij}})\]</span></p>
<p>where <span class="math inline">\(X_{ij}\)</span> are the explanatory variables and <span class="math inline">\(t_{ij}\)</span> is time.</p>
<ol type="a">
<li>If the mean is constant across time and other variables (<span class="math inline">\(X_{ij}\)</span>), and the mean is the same for all individuals, then</li>
</ol>
<p><span class="math display">\[\mu_{ij} = \mu\]</span></p>
<ol start="2" type="a">
<li>If the mean changes across time linearly and is not impacted by other variables (<span class="math inline">\(X_{i}\)</span>), and is the same for all individuals, then</li>
</ol>
<p><span class="math display">\[\mu_{ij} = \beta_0 + \beta_1 t_{ij}\]</span></p>
<ol start="3" type="a">
<li>If the mean changes across time with time-varying variables (<span class="math inline">\(X_{ij}\)</span>) and is the same for all individuals, then</li>
</ol>
<p><span class="math display">\[\mu_{ij} = \beta_0 + \beta_1 x_{ij}\]</span></p>
<p>Now, lets go back to interpreting coefficients of our models</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># unstructured covariance</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>marg_mod <span class="ot">&lt;-</span> <span class="fu">gls</span>(measurements <span class="sc">~</span> <span class="fu">factor</span>(group) <span class="sc">+</span> time, <span class="at">data =</span> long_TLC, <span class="at">corr =</span> <span class="fu">corSymm</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    id), <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> <span class="fu">as.factor</span>(level)), <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(marg_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: measurements ~ factor(group) + time 
  Data: long_TLC 
       AIC      BIC    logLik
  2583.433 2635.224 -1278.716

Correlation Structure: General
 Formula: ~1 | id 
 Parameter estimate(s):
 Correlation: 
  1     2     3    
2 0.124            
3 0.247 0.856      
4 0.518 0.455 0.522
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | as.factor(level) 
 Parameter estimates:
   lead0    lead1    lead4    lead6 
1.000000 1.836722 1.583388 1.437453 

Coefficients:
                           Value Std.Error  t-value p-value
(Intercept)            26.053146 0.6930432 37.59238  0.0000
factor(group)Treatment -2.012020 0.9786776 -2.05586  0.0404
time                   -0.399965 0.0862719 -4.63610  0.0000

 Correlation: 
                       (Intr) fct()T
factor(group)Treatment -0.706       
time                   -0.054  0.000

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.3061017 -0.7995745 -0.3107700  0.3410439  5.5215819 

Residual standard error: 5.324253 
Degrees of freedom: 400 total; 397 residual</code></pre>
</div>
</div>
<p><span class="math inline">\(\beta_{trt}\)</span> and <span class="math inline">\(\beta_{T}\)</span> represents the estimated population mean change.</p>
<p>The general interpretation for these coeffiecients when <span class="math inline">\(X_{ij}\)</span> is continuous, is that a unit difference in <span class="math inline">\(X\)</span> leads to a <span class="math inline">\(\beta_1\)</span> difference in overall mean response while holding all other variables constant.</p>
<p>Lets interpret these coefficients in the context of the TLC data.</p>
<p><strong>Interpretation</strong>:</p>
<p><span class="math inline">\(\beta_{trt}\)</span>: Among the treatment group, the average population change of blood lead levels (BLL) decreases by 2 in comparison to the control group.</p>
<p><span class="math inline">\(\beta_{T}\)</span>: Among the control and treatment groups, blood lead levels (BLL) decreases by 0.40 (<span class="math inline">\(\beta_{T}\)</span>) for every one-unit increase in time (<span class="math inline">\(T\)</span>).</p>
<p><span class="math inline">\(\beta_{0}\)</span>: Among the control and treatment group, the average population change of blood lead levels (BLL) increases by 26 and is constant over time.</p>
<p><strong>How would our interpretation change after adding an interaction term?</strong></p>
<p>Consider the following model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># unstructured covariance</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>marg_mod_inter <span class="ot">&lt;-</span> <span class="fu">gls</span>(measurements <span class="sc">~</span> <span class="fu">factor</span>(group) <span class="sc">+</span> time <span class="sc">+</span> <span class="fu">factor</span>(group)<span class="sc">:</span>time, <span class="at">data =</span> long_TLC,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">corr =</span> <span class="fu">corSymm</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> id), <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> <span class="fu">as.factor</span>(level)),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(marg_mod_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: measurements ~ factor(group) + time + factor(group):time 
  Data: long_TLC 
       AIC      BIC    logLik
  2586.646 2642.386 -1279.323

Correlation Structure: General
 Formula: ~1 | id 
 Parameter estimate(s):
 Correlation: 
  1     2     3    
2 0.132            
3 0.271 0.846      
4 0.543 0.406 0.495
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | as.factor(level) 
 Parameter estimates:
   lead0    lead1    lead4    lead6 
1.000000 1.833984 1.551842 1.439514 

Coefficients:
                                Value Std.Error  t-value p-value
(Intercept)                 26.039582 0.6940593 37.51780  0.0000
factor(group)Treatment      -1.938410 0.9815481 -1.97485  0.0490
time                        -0.368743 0.1223416 -3.01404  0.0027
factor(group)Treatment:time -0.169559 0.1730172 -0.98001  0.3277

 Correlation: 
                            (Intr) fct()T time  
factor(group)Treatment      -0.707              
time                        -0.077  0.054       
factor(group)Treatment:time  0.054 -0.077 -0.707

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.2991338 -0.7973523 -0.2854752  0.3570825  5.6284768 

Residual standard error: 5.310688 
Degrees of freedom: 400 total; 396 residual</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<p><span class="math inline">\(\beta_{0}\)</span>: Among the control and treatment groups, the average population change of blood lead levels (BLL) increases by 26 and is constant over time.</p>
<p><span class="math inline">\(\beta_{trt}\)</span>: Among the treatment group, the average population change of blood lead levels (BLL) decreases by 1.93 in comparison to the control group.</p>
<p><span class="math inline">\(\beta_{T}\)</span>: Among the control group, blood lead levels (BLL) decreases by 0.40 (<span class="math inline">\(\beta_{T}\)</span>) for every one-unit increase in time (<span class="math inline">\(T\)</span>).</p>
<p><span class="math inline">\(\beta_{T} + \beta_{trt:T}\)</span>: Among the treatment groups, blood lead levels (BLL) decreases by 2.09 for every one-unit increase in time (<span class="math inline">\(T\)</span>).</p>
<p><span class="math inline">\(\beta_{trt:T}\)</span>: Comparing the treatment and control groups, the difference in the mean change of blood lead levels (BLL) is 0.20 less among the patients in the treatment group compared to the control group for every one-unit increase in time (<span class="math inline">\(T\)</span>).</p>
<p><strong>How would this change if time was categorical?</strong></p>
<p>Consider the Response Profiles Analysis case with no interaction terms first:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># unstructured covariance</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>marg_mod_resp_prof <span class="ot">&lt;-</span> <span class="fu">gls</span>(measurements <span class="sc">~</span> <span class="fu">factor</span>(group) <span class="sc">+</span> <span class="fu">factor</span>(level), <span class="at">data =</span> long_TLC,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">corr =</span> <span class="fu">corSymm</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> id), <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> <span class="fu">as.factor</span>(level)),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(marg_mod_resp_prof)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: measurements ~ factor(group) + factor(level) 
  Data: long_TLC 
       AIC      BIC    logLik
  2525.171 2584.854 -1247.585

Correlation Structure: General
 Formula: ~1 | id 
 Parameter estimate(s):
 Correlation: 
  1     2     3    
2 0.334            
3 0.407 0.822      
4 0.551 0.512 0.550
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | as.factor(level) 
 Parameter estimates:
   lead0    lead1    lead4    lead6 
1.000000 1.567427 1.478108 1.484947 

Coefficients:
                           Value Std.Error  t-value p-value
(Intercept)            27.412077 0.7104365 38.58484  0.0000
factor(group)Treatment -2.012154 0.9786870 -2.05597  0.0404
factor(level)lead1     -7.315000 0.7993312 -9.15140  0.0000
factor(level)lead4     -6.614000 0.7247826 -9.12549  0.0000
factor(level)lead6     -4.202000 0.6448475 -6.51627  0.0000

 Correlation: 
                       (Intr) fct()T fct()1 fct()4
factor(group)Treatment -0.689                     
factor(level)lead1     -0.222  0.000              
factor(level)lead4     -0.205  0.000  0.814       
factor(level)lead6     -0.105  0.000  0.437  0.446

Standardized residuals:
        Min          Q1         Med          Q3         Max 
-2.23559962 -0.64349371 -0.04593541  0.61603790  5.58341207 

Residual standard error: 5.150368 
Degrees of freedom: 400 total; 395 residual</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<p><span class="math inline">\(\beta_{0}\)</span>: Among the control and treatment groups, the average population change of blood lead levels (BLL) increases by 27.41 and is constant over time.</p>
<p><span class="math inline">\(\beta_{trt}\)</span>: Among the treatment group, the average population change of blood lead levels (BLL) decreases by 2.01 in comparison to the control group.</p>
<p><span class="math inline">\(\beta_{T_1}, \beta_{T_4}, \beta_{T_6}\)</span>: represent the average change in blood lead levels (BLL) among the population (e.g.&nbsp;both control and treatment groups) relative to baseline which is the reference group for each time variable (dichotomous indicator variable).</p>
<p>For example, the average change in blood lead levels (BLL) among the population is 7.31 less compared to the baseline measure.</p>
<p><strong>How would this change if an interaction term was included in the model?</strong></p>
<p>Consider the Response Profiles Analysis case with no interaction terms first:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># unstructured covariance</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>marg_mod_resp_prof <span class="ot">&lt;-</span> <span class="fu">gls</span>(measurements <span class="sc">~</span> <span class="fu">factor</span>(group) <span class="sc">+</span> <span class="fu">factor</span>(level) <span class="sc">+</span> <span class="fu">factor</span>(group)<span class="sc">:</span><span class="fu">factor</span>(level),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> long_TLC, <span class="at">corr =</span> <span class="fu">corSymm</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> id), <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">as.factor</span>(level)), <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(marg_mod_resp_prof)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: measurements ~ factor(group) + factor(level) + factor(group):factor(level) 
  Data: long_TLC 
       AIC      BIC    logLik
  2452.076 2523.559 -1208.038

Correlation Structure: General
 Formula: ~1 | id 
 Parameter estimate(s):
 Correlation: 
  1     2     3    
2 0.571            
3 0.570 0.775      
4 0.577 0.582 0.581
Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | as.factor(level) 
 Parameter estimates:
   lead0    lead1    lead4    lead6 
1.000000 1.325877 1.370471 1.524816 

Coefficients:
                                            Value Std.Error   t-value p-value
(Intercept)                                26.272 0.7102892  36.98775  0.0000
factor(group)Treatment                      0.268 1.0045006   0.26680  0.7898
factor(level)lead1                         -1.612 0.7919151  -2.03557  0.0425
factor(level)lead4                         -2.202 0.8149218  -2.70210  0.0072
factor(level)lead6                         -2.626 0.8885198  -2.95548  0.0033
factor(group)Treatment:factor(level)lead1 -11.406 1.1199371 -10.18450  0.0000
factor(group)Treatment:factor(level)lead4  -8.824 1.1524735  -7.65658  0.0000
factor(group)Treatment:factor(level)lead6  -3.152 1.2565568  -2.50844  0.0125

 Correlation: 
                                          (Intr) fct()T fct()1 fct()4 fct()6
factor(group)Treatment                    -0.707                            
factor(level)lead1                        -0.218  0.154                     
factor(level)lead4                        -0.191  0.135  0.680              
factor(level)lead6                        -0.096  0.068  0.386  0.385       
factor(group)Treatment:factor(level)lead1  0.154 -0.218 -0.707 -0.481 -0.273
factor(group)Treatment:factor(level)lead4  0.135 -0.191 -0.481 -0.707 -0.272
factor(group)Treatment:factor(level)lead6  0.068 -0.096 -0.273 -0.272 -0.707
                                          f()T:()1 f()T:()4
factor(group)Treatment                                     
factor(level)lead1                                         
factor(level)lead4                                         
factor(level)lead6                                         
factor(group)Treatment:factor(level)lead1                  
factor(group)Treatment:factor(level)lead4  0.680           
factor(group)Treatment:factor(level)lead6  0.386    0.385  

Standardized residuals:
       Min         Q1        Med         Q3        Max 
-2.1756516 -0.6849999 -0.1515556  0.5294195  5.6327729 

Residual standard error: 5.022503 
Degrees of freedom: 400 total; 392 residual</code></pre>
</div>
</div>
<p><strong>Interpretation of Interaction Term Parameters</strong>:</p>
<p><span class="math inline">\(\beta_{T_1}, \beta_{T_4}, \beta_{T_6}\)</span>: represent the average change in blood lead levels (BLL) among the control group relative to baseline which is the reference group in this case for each time variable (dichotomous indicator variable).</p>
<p><span class="math inline">\(\beta_{T_1} + \beta_{trt:T1}, \beta_{T_4} + \beta_{trt:T4}, \beta_{T_6} + \beta_{trt:T6}\)</span>: represent the average change in blood lead levels (BLL) among the treatment group compared to control group relative to baseline which is the reference group in this case for each time variable (dichotomous indicator variable).</p>
<p>For example, the average change in blood lead levels (BLL) among the treatment group at week 1 compared to baseline is 13.02 less (<span class="math inline">\(\beta_{T_1} + \beta_{trt:T1}\)</span>) in comparison to the control group at visit 1. Notice that there are two references here in our interpretation: the group (treatment vs control) and the time point (week 1 vs baseline).</p>
<p><span class="math inline">\(\beta_{trt:T1}, \beta_{trt:T4}, \beta_{trt:T6}\)</span>: represent the average difference in mean blood lead levels (BLL) between treatment groups at the different time points in comparison to baseline which is the reference group.</p>
<p>For example, the average difference in mean blood lead levels (BLL) from baseline to week 1 was 11.40 (<span class="math inline">\(\beta_{trt:T1}\)</span>) between treatment groups.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Longi_GEE.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Marginal Model (GEE)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Longi_mixeffect.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Mixed Effects Model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>